sample_scraped_reviews = [
    (
        "March 16, 2023",
        "5.0",
        "Like the smell",
        "A nice fresh smell and stays with your laundry for a while.",
    ),
    (
        "March 6, 2023",
        "5.0",
        "Best scent that lasts!",
        "Practical to use and has the best scent that truly lasts for weeks!",
    ),
    (
        "February 25, 2023",
        "5.0",
        "The best smell",
        "This is my favorite smell for detergent.  I reorder consistently!",
    ),
    ("February 23, 2023", "5.0", "A+", "A+"),
    (
        "February 11, 2023",
        "5.0",
        "Pricey side",
        "So far cloths seem to get clean,not enough good smell fresh clean if you like that",
    ),
    ("February 8, 2023", "5.0", "Great", "Gift needed 👍"),
    (
        "February 8, 2023",
        "5.0",
        "Easier then the cup and no measuring",
        "I never get any where close to the loads on a liquid bottle and even with the lowest amount the clothes never seemed clean and still smelled. I use 2 of these and clothes come out smelling clean and looking clean.",
    ),
    (
        "February 5, 2023",
        "4.0",
        "All I use",
        "Love this detergent!! It’s all I use and makes all my clothes freash smelling and perfectly clean",
    ),
    (
        "January 19, 2023",
        "5.0",
        "Best product ever",
        "My son plays basketball and football. This tide sports for breeze is amazing it attacks any older I would purchase this from now on.",
    ),
    (
        "January 14, 2023",
        "5.0",
        "The best clean",
        "The pods are easy to use compared to the liquid detergent.  The added Febreze really boosts the fragrance!",
    ),
    ("January 13, 2023", "5.0", "Great", "Works great wife loves it"),
    (
        "January 11, 2023",
        "5.0",
        "My favorite detergent",
        "I’m confident that my clothes will come out clean and smelling fresh every time!",
    ),
    (
        "December 31, 2022",
        "5.0",
        "Febreeze Addition Makes the Sport Type worth the cost",
        "I didn’t use Tide u til I bought the pods with the Febreeze addition. I love the smell and it works well on my and my son’s workout clothes. We wash these smelly items separately and these Tide pods work well to get the sweat smell out of the clothes.",
    ),
    (
        "December 30, 2022",
        "4.0",
        "Best on the market",
        "Not much to say here: it's easy to use - just toss three in the laundry for a larger load and you're ready to go. If you find that it doesn't dissolve completely, one method would be to put in the pods first instead of putting it in after your laundry. I find that this method is the \"cleanest\" and ensure efficiency.",
    ),
    (
        "December 26, 2022",
        "5.0",
        "These get the funk out.",
        "If you do a lot of sweating at the gym or any type of sport and your clothes get a little funky this will take care of them. One scoop of OxiClean Odorblasters and this works amazing.",
    ),
    (
        "December 7, 2022",
        "4.0",
        "I really like Tide and",
        "I am a long time Tide user.  I purchased this because my son has to go to a laundrymat to do clothes washing.  These pods are easy to carry with laundry and no spills or  drips in the car from the bottles of Tide and fabric sanitizer.",
    ),
    ("December 5, 2022", "5.0", "Great laundry detergent", "Lo be it"),
    ("November 29, 2022", "4.0", "Good value", "Good value"),
    (
        "November 25, 2022",
        "5.0",
        "Clean & Fresh on deck!",
        "Tide Sports with Febrez is my go to Laundry detergent.  It cleans your clothes, and keeps them smelling fresh.",
    ),
    (
        "November 20, 2022",
        "4.0",
        "Hard to open",
        "The container is hard to open for my wife. She can not squeeze the lid enough (small hands) to compress it to allow opening. Pods work well otherwise.",
    ),
]
